---
# Instead of testing that the deployment config is removed, we test that the pods
# are cleaned up afterwards
- name: Test|Check that all configmaps have been removed
  shell: oc get configmap --namespace={{ namespace }} {{ item }} 2>&1
  register: result
  retries: 50
  delay: 10
  failed_when:
    - '"not found" not in result.stdout'
  until: '"not found" in result.stdout'
  with_items:
    - '{{ keycloak_configmap_name }}'

- name: Test|Check that all secrets have been removed
  shell: oc get secret --namespace={{ namespace }} {{ item }} 2>&1
  register: result
  retries: 50
  delay: 10
  failed_when:
    - '"not found" not in result.stdout'
  until: '"not found" in result.stdout'
  with_items:
    - '{{ keycloak_secret_name }}'

- block:
  - name: Test|Check that all pods have been removed
    shell: oc get pods --namespace={{ namespace }} --selector="deploymentconfig in (keycloak,postgres)" 2>&1
    register: result
    retries: 50
    delay: 10
    failed_when:
      - '"No resources found." not in result.stdout'
    until: '"No resources found." in result.stdout'

  - name: Test|Check that the keycloak route has been removed
    shell: oc get route --namespace={{ namespace }} {{ keycloak_route_name }} 2>&1
    register: result
    retries: 50
    delay: 10
    failed_when:
      - '"not found" not in result.stdout'
    until: '"not found" in result.stdout'

  - name: Test|Check that all services have been removed
    shell: oc get service --namespace={{ namespace }} {{ item }} 2>&1
    register: result
    retries: 50
    delay: 10
    failed_when:
      - '"not found" not in result.stdout'
    until: '"not found" in result.stdout'
    with_items:
      - '{{ keycloak_service_name }}'
      - '{{ postgres_service_name }}'

  - name: Test|Check that all secrets have been removed
    shell: oc get secret --namespace={{ namespace }} {{ item }} 2>&1
    register: result
    retries: 50
    delay: 10
    failed_when:
      - '"not found" not in result.stdout'
    until: '"not found" in result.stdout'
    with_items:
      - '{{ postgres_secret_name }}'

  - name: Test|Check that all persistent volume claims have been removed
    shell: oc get pvc --namespace={{ namespace }} {{ item }} 2>&1
    register: result
    retries: 50
    delay: 10
    failed_when:
      - '"not found" not in result.stdout'
    until: '"not found" in result.stdout'
    with_items:
    - '{{ keycloak_pv_claim_name }}'
    - '{{ postgres_service_name }}'
  when: not USE_SHARED_SERVICE

- block:
  - name: Generate keycloak auth token for {{ ADMIN_USERNAME }}
    uri:
      url: "{{ _apb_provision_creds.URI }}/auth/realms/{{ keycloak_admin_realm_name }}/protocol/openid-connect/token"
      method: POST
      body: "client_id=admin-cli&username={{ ADMIN_USERNAME }}&password={{ ADMIN_PASSWORD }}&grant_type=password"
      validate_certs: no
    register: keycloak_auth_response
    retries: 20
    delay: 2
    until: keycloak_auth_response.status == 503 or
           keycloak_auth_response.status in [200, 401, 403]
    ignore_errors: yes

  - debug:
      var: keycloak_auth_response
      verbosity: 2

  - name: Test|Check that keycloak {{ _apb_provision_creds.REALM }} realm exists
    uri:
      url: "{{ _apb_provision_creds.URI }}/auth/admin/realms/{{ _apb_provision_creds.REALM }}"
      method: GET
      validate_certs: no
      body_format: json
      headers:
        Authorization: "Bearer {{ keycloak_auth_response.json.access_token }}"
      status_code: [200]
      return_content: yes
    register: keycloak_realm_exists

  - name: Test|Check that keycloak {{ _apb_provision_creds.USERNAME }} user exists
    uri:
      url: "{{ _apb_provision_creds.URI }}/auth/admin/realms/{{ _apb_provision_creds.REALM }}/users/{{ _apb_provision_creds.USERID }}"
      method: GET
      validate_certs: no
      body_format: json
      headers:
        Authorization: "Bearer {{ keycloak_auth_response.json.access_token }}"
      status_code: [404]
      return_content: yes
    register: keycloak_user_exists
  when: USE_SHARED_SERVICE