---
- name: Test|Check that {{ keycloak_secret_name }}-{{ CLIENT_ID | lower }}-{{ CLIENT_TYPE }} secret has been removed
  shell: "oc get secrets/{{ keycloak_secret_name }}-{{ CLIENT_ID | lower }}-{{ CLIENT_TYPE }} -o name 2>&1"
  register: result
  retries: 50
  delay: 10
  failed_when:
    - '"not found" not in result.stdout'
  until: '"not found" in result.stdout'

- name: Test|Generate keycloak auth token for {{ _apb_provision_creds.USERNAME }}
  uri:
    url: "{{ _apb_provision_creds.URI }}/auth/realms/{{ _apb_provision_creds.LOGIN_REALM }}/protocol/openid-connect/token"
    method: POST
    body: "client_id=admin-cli&username={{ _apb_provision_creds.USERNAME }}&password={{ _apb_provision_creds.PASSWORD }}&grant_type=password"
    validate_certs: no
  register: keycloak_auth_response
  retries: 20
  delay: 2
  until: keycloak_auth_response.status == 503 or
         keycloak_auth_response.status in [200, 401, 403]
  ignore_errors: yes

- debug:
    var: keycloak_auth_response
    verbosity: 2

- name: Test|Check that keycloak {{ _apb_bind_creds.clientId }} client does not exist in {{ _apb_provision_creds.REALM }} realm
  uri:
    url: "{{ _apb_provision_creds.URI }}/auth/admin/realms/{{ _apb_provision_creds.REALM }}/clients/{{ _apb_bind_creds.id }}"
    method: GET
    validate_certs: no
    body_format: json
    headers:
      Authorization: "Bearer {{ keycloak_auth_response.json.access_token }}"
    status_code: [404]
    return_content: yes
  register: keycloak_client_exists