---
- name: Delete keycloak secrets
  k8s_v1_secret:
    name: '{{ item }}'
    namespace: '{{ namespace }}'
    state: absent
  with_items:
  - '{{ keycloak_secret_name }}'

- name: Delete configmaps
  k8s_v1_config_map:
    name: '{{ item }}'
    namespace: '{{ namespace }}'
    state: absent
  with_items:
  - '{{ keycloak_configmap_name }}'