---
- block:
  - include_tasks: deprovision-keycloak.yml
    when: USE_SHARED_SERVICE is undefined or
          not USE_SHARED_SERVICE
  - include_tasks: cleanup-keycloak.yml
    when:
      - USE_SHARED_SERVICE is defined
      - USE_SHARED_SERVICE
  always:
  - include_tasks: cleanup-resources.yml