FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.version"="0.1.0"
LABEL "com.redhat.apb.spec"=\
"bmFtZToga2V5Y2xvYWstYXBiCmltYWdlOiBmZWVkaGVucnkva2V5Y2xvYWstYXBiCmRlc2NyaXB0\
aW9uOiBLZXljbG9hayAtIHNlY3VyZSBrZXkvdmFsdWUgc3RvcmUKYmluZGFibGU6IFRydWUKYXN5\
bmM6IG9wdGlvbmFsCnRhZ3M6IAogIC0gbW9iaWxlLXNlcnZpY2UKbWV0YWRhdGE6CiAgZGlzcGxh\
eU5hbWU6IEtleWNsb2FrIChBUEIpCnBsYW5zOgogIC0gbmFtZTogZGVmYXVsdAogICAgZGVzY3Jp\
cHRpb246IERlcGxveSBrZXljbG9hay1hcGIKICAgIGZyZWU6IFRydWUKICAgIG1ldGFkYXRhOiB7\
fQogICAgcGFyYW1ldGVyczogCiAgICAtIG5hbWU6IEFETUlOX05BTUUKICAgICAgcmVxdWlyZWQ6\
IFRydWUKICAgICAgZGVmYXVsdDogYWRtaW4KICAgICAgdHlwZTogc3RyaW5nCiAgICAgIHRpdGxl\
OiBLZXljbG9hayBhZG1pbiB1c2VybmFtZQogICAgLSBuYW1lOiBBRE1JTl9QQVNTV09SRAogICAg\
ICByZXF1aXJlZDogVHJ1ZQogICAgICBkZWZhdWx0OiBhZG1pbgogICAgICB0eXBlOiBzdHJpbmcK\
ICAgICAgdGl0bGU6IEtleWNsb2FrIGFkbWluIHBhc3N3b3JkCg=="

COPY playbooks /opt/apb/actions
COPY roles /opt/ansible/roles
RUN chmod -R g=u /opt/{ansible,apb}
USER apb
